[package]
name = "graphviz-ffi-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["clib-graphviz"]

[dependencies]
clib-graphviz = {path = "./clib-graphviz"}